name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for using the FGVR library and contribute by providing this feedback! I will get back to you as soon as possible.'' first issue'
        pr-message: 'Thanks for using the FGVR library and contribute by providing this feedback! I will get back to you as soon as possible.'' first pr'
